version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wallet
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: wallet
    volumes:
      - .:/usr/src/app

volumes:
  db-data:
